name: covid19
description: An app for tracking COVID cases across the globe and counties

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  http: ^0.13.4
  intl: ^0.17.0
  splashscreen: ^1.2.0
  progress_indicators: ^1.0.0
  pytorch_mobile: ^0.2.1
  image_picker: ^0.8.4+11
  tflite: ^1.0.2
  hawk_fab_menu: ^1.1.2
  tflite_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/models/
    - assets/labels/labels.csv


  fonts:
    - family: MyIcons
      fonts:
        - asset: icons/MyIcons.ttf

    - family: MyFont
      fonts:
        - asset: font/SegoeUI.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

